# Use the official PostgreSQL image as the base image
FROM postgres:16-alpine

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=tykon
ENV POSTGRES_PASSWORD=password

# Expose the PostgreSQL port
EXPOSE 5432

# Add any custom initialization scripts if needed
# COPY ./init.sql /docker-entrypoint-initdb.d/

# Set the default command
CMD ["postgres"] 